version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app-conduktor
    ports:
      - "8080:8080"
    environment:
      # KAFKA_BOOTSTRAP_SERVERS: 127.0.0.1:9092
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      TOPIC: persons-topic
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
